-- ==============================================================================
-- ⚠️  DEPRECATED — DO NOT EDIT THIS FILE ⚠️
--
-- This file holds 78 hand-maintained CREATE TABLE statements that predate the
-- migration of this CRM onto the open-mercato framework. It is the single
-- largest source of schema drift, multi-tenant security risk, and AI/search
-- invisibility in the codebase. It is scheduled for deletion as each table is
-- migrated into a proper mercato module (see .ai/specs/SPEC-MERCATO-REBUILD.md).
--
-- DO NOT add new tables or columns here. DO NOT edit existing definitions.
-- A pre-commit hook (scripts/check-forbidden-patterns.mjs) will reject any
-- additions. New persistent state belongs in a mercato module's data/entities.ts
-- with migrations generated by `yarn db:generate`. See AGENTS.md → "Forbidden
-- Patterns" for the full rationale.
--
-- The only legitimate edit to this file is DELETION of a table that has been
-- successfully ported to a mercato module and verified in production.
-- ==============================================================================
--
-- Original header (kept for historical reference):
-- CRM Custom Tables Setup
-- Run this after initializing Open Mercato: psql -U crm -d crm < setup-tables.sql
-- ==============================================================================

-- Form Builder (standalone forms)

-- Landing Pages


-- Email



-- Billing / Credits

INSERT INTO credit_packages (name, credit_amount, price, sort_order) VALUES
  ('Starter', 10, 10, 1), ('Growth', 25, 25, 2), ('Pro', 50, 50, 3) ON CONFLICT DO NOTHING;

-- Payments


-- Notes & Tasks: MIGRATED to packages/core/src/modules/customers/data/entities.ts
-- (CustomerContactNote, CustomerTask) — see SPEC-061 tier 0. Tables managed
-- by Migration20260409154143.ts. Definitions deleted from this file as part
-- of the tier 0 cutover (commit history preserves them).

-- AI Usage

-- Business Profiles: MIGRATED to packages/core/src/modules/customers/data/entities.ts
-- (CustomerBusinessProfile) — see SPEC-061 tier 0.

-- Stage Automations
-- Calendar & Booking

-- Google Calendar

-- SMS

-- Courses

-- Student auth for course portal


-- Sequences (Drip / Follow-up)




-- Email status on contacts (for bounce/complaint tracking)

-- Response Templates

-- Contact Engagement Scoring + Reminders: MIGRATED to packages/core/src/modules/customers/data/entities.ts
-- (CustomerContactEngagementScore, CustomerEngagementEvent, CustomerReminder)
-- — see SPEC-061 tier 0. The contact_engagement_scores schema gained a
-- created_at column, engagement_events gained tenant_id, and reminders
-- gained updated_at + deleted_at as part of the tier 0 migration.


-- Outbound Webhooks


-- Contact Attachments: MIGRATED to packages/core/src/modules/customers/data/entities.ts
-- (CustomerContactAttachment) — see SPEC-061 tier 0. Schema gained
-- updated_at + deleted_at columns. The file upload route at
-- /api/contacts/[id]/attachments STAYS as a holdover because the mercato
-- CRUD route is metadata-only and doesn't handle multipart file uploads
-- yet — see SPEC-061 §"Tier 0 cutover" for the deferred work.

-- Automation Rules


-- Email Preferences


-- Send Time Optimization: MIGRATED to packages/core/src/modules/customers/data/entities.ts
-- (CustomerContactOpenTime) — see SPEC-061 tier 0. Schema gained tenant_id
-- column. The /api/email/send-time analytics route is a holdover that still
-- queries this table via raw knex — see SPEC-061 §"Tier 0 cutover".

-- Email Style Templates


-- Surveys & Forms


-- Funnels



-- Funnel extensions (upsell/downsell support)



-- Live Chat


-- Affiliate Campaigns

-- Affiliates



-- Unified Inbox

-- Inbox internal notes

-- Inbox AI draft settings
-- Sequence branching support

-- Email Connections (Gmail, Outlook, SMTP)

-- ESP Connections (Resend, SendGrid, SES, Mailgun) for bulk campaigns

-- ESP Sender Addresses (multiple from addresses per ESP connection)

-- Email Lists (mailing lists / contact groups)


-- Email Routing (per-feature provider assignment)

-- Stripe Connect

-- Twilio Connections

-- AI Persona columns on business_profiles

-- Website scan fields

-- Pipeline mode (deals vs journey)

-- Email sentiment tracking

-- AI Digest settings

-- Meeting Prep Briefs

-- Task Templates: MIGRATED to packages/core/src/modules/customers/data/entities.ts
-- (CustomerTaskTemplate) — see SPEC-061 tier 0. Schema gained deleted_at
-- column. The /api/task-templates/apply route is a holdover that spawns
-- tasks from a template and still queries this table via raw knex.

-- Email intake mode

-- Interface mode (simple vs advanced) and onboarding status

-- Brand Voice Engine

-- Chat widget enhancements (slug, branding, public page)

-- Done
SELECT 'All custom tables created successfully' AS status;
