import { Migration } from '@mikro-orm/migrations';

/* Blind search index for encrypted contact, company and deal fields
 * (2026-09-25).
 *
 * customer_search_tokens holds HMAC-SHA256 hashes of normalized name / email /
 * phone / title tokens under a per-tenant key derived from the tenant data key
 * (packages/shared/src/lib/encryption/searchTokens.ts). Search matches hashes
 * in SQL instead of decrypting an organization's latest 2,000 contacts.
 * Indexes: (tenant_id, organization_id, token_hash) for lookups, and a unique
 * (entity_id, entity_type, field, token_hash) that makes inserts idempotent and
 * serves per-entity replace/delete. Triggers drop an entity's tokens on any
 * hard delete or soft delete, whatever path deletes it.
 *
 * Also purges plaintext-equivalent copies of encrypted fields that the Open
 * Mercato query index and search module wrote (unkeyed SHA-256 search_tokens,
 * the search_text aggregate, vector_search display text); see
 * searchIndexPurgeSql. The tokens themselves are filled by
 * scripts/reindex-customer-search.ts (needs the tenant key, so not SQL).
 *
 * Idempotent; production applied it with
 * `node /app/scripts/reindex-customer-search.cjs --apply-migration --execute`.
 *
 * SELF-CONTAINED ON PURPOSE: the SQL is inlined, not imported from
 * ../lib/searchIndexSchema. The runner image loads migrations from source and
 * cannot resolve a sibling lib import ("Cannot find module"), which failed
 * `mercato db migrate`. lib/searchIndexSchema.ts keeps the same statements for
 * the script and tests; migrationsSelfContained.test.ts asserts they match and
 * that no migration imports outside its folder. */
const UP_SQL: string[] = [
  `create table if not exists "customer_search_tokens" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" uuid not null,
    "organization_id" uuid not null,
    "entity_type" text not null,
    "entity_id" uuid not null,
    "field" text not null,
    "token_hash" text not null,
    "created_at" timestamptz not null default now(),
    constraint "customer_search_tokens_entity_type_chk" check ("entity_type" in ('person', 'company', 'deal'))
  );`,
  `create index if not exists "customer_search_tokens_lookup_idx" on "customer_search_tokens" ("tenant_id", "organization_id", "token_hash");`,
  `create unique index if not exists "customer_search_tokens_entity_uniq" on "customer_search_tokens" ("entity_id", "entity_type", "field", "token_hash");`,
  `create or replace function "customer_search_tokens_on_contact_change"() returns trigger language plpgsql as $$
begin
  if (TG_OP = 'DELETE') then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" in ('person', 'company');
    return OLD;
  end if;
  if (NEW."deleted_at" is not null and OLD."deleted_at" is null) then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" in ('person', 'company');
  end if;
  return NEW;
end
$$;`,
  `create or replace function "customer_search_tokens_on_deal_change"() returns trigger language plpgsql as $$
begin
  if (TG_OP = 'DELETE') then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" = 'deal';
    return OLD;
  end if;
  if (NEW."deleted_at" is not null and OLD."deleted_at" is null) then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" = 'deal';
  end if;
  return NEW;
end
$$;`,
  `create or replace function "customer_search_tokens_on_person_delete"() returns trigger language plpgsql as $$
begin
  delete from "customer_search_tokens"
   where "entity_id" = OLD."entity_id" and "entity_type" = 'person'
     and "field" in ('first_name', 'last_name', 'preferred_name', 'job_title');
  return OLD;
end
$$;`,
  `create or replace function "customer_search_tokens_on_company_delete"() returns trigger language plpgsql as $$
begin
  delete from "customer_search_tokens"
   where "entity_id" = OLD."entity_id" and "entity_type" = 'company'
     and "field" in ('legal_name', 'brand_name', 'domain', 'website_url');
  return OLD;
end
$$;`,
  `drop trigger if exists "customer_search_tokens_contact_trg" on "customer_entities";`,
  `create trigger "customer_search_tokens_contact_trg" after delete or update of "deleted_at" on "customer_entities" for each row execute function "customer_search_tokens_on_contact_change"();`,
  `drop trigger if exists "customer_search_tokens_deal_trg" on "customer_deals";`,
  `create trigger "customer_search_tokens_deal_trg" after delete or update of "deleted_at" on "customer_deals" for each row execute function "customer_search_tokens_on_deal_change"();`,
  `drop trigger if exists "customer_search_tokens_person_trg" on "customer_people";`,
  `create trigger "customer_search_tokens_person_trg" after delete on "customer_people" for each row execute function "customer_search_tokens_on_person_delete"();`,
  `drop trigger if exists "customer_search_tokens_company_trg" on "customer_companies";`,
  `create trigger "customer_search_tokens_company_trg" after delete on "customer_companies" for each row execute function "customer_search_tokens_on_company_delete"();`,
  `do $purge$ begin
  if to_regclass('search_tokens') is not null then
    delete from "search_tokens" where ("entity_type", "field") in (values ('auth:user', 'email'), ('customers:customer_address', 'name'), ('customers:customer_address', 'company_name'), ('customers:customer_address', 'address_line1'), ('customers:customer_address', 'address_line2'), ('customers:customer_address', 'city'), ('customers:customer_address', 'region'), ('customers:customer_address', 'postal_code'), ('customers:customer_address', 'country'), ('customers:customer_address', 'building_number'), ('customers:customer_address', 'flat_number'), ('customers:customer_entity', 'display_name'), ('customers:customer_entity', 'primary_email'), ('customers:customer_entity', 'primary_phone'), ('customers:customer_entity', 'next_interaction_name'), ('customers:customer_entity', 'description'), ('customers:customer_deal', 'title'), ('customers:customer_deal', 'description'), ('customers:customer_activity', 'subject'), ('customers:customer_activity', 'body'), ('customers:customer_comment', 'body'), ('customers:customer_person_profile', 'first_name'), ('customers:customer_person_profile', 'last_name'), ('customers:customer_person_profile', 'preferred_name'), ('customers:customer_person_profile', 'job_title'), ('customers:customer_person_profile', 'department'), ('customers:customer_person_profile', 'seniority'), ('customers:customer_person_profile', 'timezone'), ('customers:customer_person_profile', 'linked_in_url'), ('customers:customer_person_profile', 'twitter_url'), ('customers:customer_person_profile', 'display_name'), ('customers:customer_person_profile', 'primary_email'), ('customers:customer_person_profile', 'primary_phone'), ('customers:customer_person_profile', 'next_interaction_name'), ('customers:customer_person_profile', 'description'), ('customers:customer_company_profile', 'legal_name'), ('customers:customer_company_profile', 'brand_name'), ('customers:customer_company_profile', 'domain'), ('customers:customer_company_profile', 'website_url'), ('customers:customer_company_profile', 'industry'), ('customers:customer_company_profile', 'display_name'), ('customers:customer_company_profile', 'primary_email'), ('customers:customer_company_profile', 'primary_phone'), ('customers:customer_company_profile', 'next_interaction_name'), ('customers:customer_company_profile', 'description'), ('sales:sales_order', 'customer_snapshot'), ('sales:sales_order', 'billing_address_snapshot'), ('sales:sales_order', 'shipping_address_snapshot'), ('sales:sales_order', 'shipping_method_snapshot'), ('sales:sales_order', 'delivery_window_snapshot'), ('sales:sales_order', 'payment_method_snapshot'), ('sales:sales_order', 'totals_snapshot'), ('sales:sales_order', 'catalog_snapshot'), ('sales:sales_order', 'promotion_snapshot'), ('sales:sales_order', 'comments'), ('sales:sales_order', 'internal_notes'), ('sales:sales_order', 'metadata'), ('sales:sales_quote', 'customer_snapshot'), ('sales:sales_quote', 'billing_address_snapshot'), ('sales:sales_quote', 'shipping_address_snapshot'), ('sales:sales_quote', 'shipping_method_snapshot'), ('sales:sales_quote', 'delivery_window_snapshot'), ('sales:sales_quote', 'payment_method_snapshot'), ('sales:sales_quote', 'totals_snapshot'), ('sales:sales_quote', 'catalog_snapshot'), ('sales:sales_quote', 'promotion_snapshot'), ('sales:sales_quote', 'comments'), ('sales:sales_quote', 'internal_notes'), ('sales:sales_quote', 'metadata'), ('sales:sales_document_address', 'name'), ('sales:sales_document_address', 'purpose'), ('sales:sales_document_address', 'company_name'), ('sales:sales_document_address', 'address_line1'), ('sales:sales_document_address', 'address_line2'), ('sales:sales_document_address', 'city'), ('sales:sales_document_address', 'region'), ('sales:sales_document_address', 'postal_code'), ('sales:sales_document_address', 'country'), ('sales:sales_document_address', 'building_number'), ('sales:sales_document_address', 'flat_number'), ('sales:sales_note', 'body'), ('audit_logs:action_log', 'command_id'), ('audit_logs:action_log', 'action_label'), ('audit_logs:action_log', 'command_payload'), ('audit_logs:action_log', 'snapshot_before'), ('audit_logs:action_log', 'snapshot_after'), ('audit_logs:action_log', 'changes_json'), ('audit_logs:action_log', 'context_json'), ('audit_logs:access_log', 'resource_id'), ('audit_logs:access_log', 'fields_json'), ('audit_logs:access_log', 'context_json'), ('integrations:integration_credentials', 'credentials'), ('staff:staff_leave_request', 'note'), ('staff:staff_leave_request', 'decision_comment'), ('staff:staff_leave_request', 'unavailability_reason_value'), ('vector:vector_search', 'links'), ('vector:vector_search', 'payload'), ('vector:vector_search', 'result_title'), ('vector:vector_search', 'result_subtitle'), ('vector:vector_search', 'result_icon'), ('vector:vector_search', 'result_badge'), ('vector:vector_search', 'result_snapshot'), ('vector:vector_search', 'primary_link_href'), ('vector:vector_search', 'primary_link_label'));
  end if;
end $purge$;`,
  `do $purge$ begin
  if to_regclass('search_tokens') is not null then
    delete from "search_tokens" where "entity_type" in ('auth:user', 'customers:customer_address', 'customers:customer_entity', 'customers:customer_deal', 'customers:customer_activity', 'customers:customer_comment', 'customers:customer_person_profile', 'customers:customer_company_profile', 'sales:sales_order', 'sales:sales_quote', 'sales:sales_document_address', 'sales:sales_note', 'audit_logs:action_log', 'audit_logs:access_log', 'integrations:integration_credentials', 'staff:staff_leave_request', 'vector:vector_search') and "field" = 'search_text';
  end if;
end $purge$;`,
  `do $purge$ begin
  if to_regclass('search_tokens') is not null and to_regclass('custom_field_defs') is not null then
    delete from "search_tokens" st using "custom_field_defs" d
      where d."entity_id" = st."entity_type"
        and st."field" in ('cf:' || d."key", 'cf_' || d."key")
        and (d."config_json"::jsonb ->> 'encrypted') = 'true';
  end if;
end $purge$;`,
  `do $purge$ begin
  if to_regclass('search_tokens') is not null then
    update "search_tokens" set "token" = null where "token" is not null and "entity_type" in ('auth:user', 'customers:customer_address', 'customers:customer_entity', 'customers:customer_deal', 'customers:customer_activity', 'customers:customer_comment', 'customers:customer_person_profile', 'customers:customer_company_profile', 'sales:sales_order', 'sales:sales_quote', 'sales:sales_document_address', 'sales:sales_note', 'audit_logs:action_log', 'audit_logs:access_log', 'integrations:integration_credentials', 'staff:staff_leave_request', 'vector:vector_search');
  end if;
end $purge$;`,
  `do $purge$ begin
  if to_regclass('entity_indexes') is not null then
    update "entity_indexes" set "doc" = "doc" - 'search_text' where "entity_type" in ('auth:user', 'customers:customer_address', 'customers:customer_entity', 'customers:customer_deal', 'customers:customer_activity', 'customers:customer_comment', 'customers:customer_person_profile', 'customers:customer_company_profile', 'sales:sales_order', 'sales:sales_quote', 'sales:sales_document_address', 'sales:sales_note', 'audit_logs:action_log', 'audit_logs:access_log', 'integrations:integration_credentials', 'staff:staff_leave_request', 'vector:vector_search') and "doc" -> 'search_text' is not null;
  end if;
end $purge$;`,
  `do $purge$ begin
  if to_regclass('vector_search') is not null then
    delete from "vector_search" where "entity_id" in ('auth:user', 'customers:customer_address', 'customers:customer_entity', 'customers:customer_deal', 'customers:customer_activity', 'customers:customer_comment', 'customers:customer_person_profile', 'customers:customer_company_profile', 'sales:sales_order', 'sales:sales_quote', 'sales:sales_document_address', 'sales:sales_note', 'audit_logs:action_log', 'audit_logs:access_log', 'integrations:integration_credentials', 'staff:staff_leave_request', 'vector:vector_search');
  end if;
end $purge$;`,
]

const DOWN_SQL: string[] = [
  `drop trigger if exists "customer_search_tokens_contact_trg" on "customer_entities";`,
  `drop trigger if exists "customer_search_tokens_deal_trg" on "customer_deals";`,
  `drop trigger if exists "customer_search_tokens_person_trg" on "customer_people";`,
  `drop trigger if exists "customer_search_tokens_company_trg" on "customer_companies";`,
  `drop function if exists "customer_search_tokens_on_contact_change"();`,
  `drop function if exists "customer_search_tokens_on_deal_change"();`,
  `drop function if exists "customer_search_tokens_on_person_delete"();`,
  `drop function if exists "customer_search_tokens_on_company_delete"();`,
  `drop table if exists "customer_search_tokens";`,
]

export class Migration20260925120000 extends Migration {

  override async up(): Promise<void> {
    for (const sql of UP_SQL) this.addSql(sql);
  }

  override async down(): Promise<void> {
    // The purge is not reversible (and must not be: it removed plaintext copies).
    for (const sql of DOWN_SQL) this.addSql(sql);
  }

}
