import { DEFAULT_ENCRYPTION_MAPS } from '../../entities/lib/encryptionDefaults'

/**
 * Schema and one-time purge for the blind contact search index. Shared by
 * Migration20260925120000 and scripts/reindex-customer-search.ts
 * (`--apply-migration`, for the production box where the migrator does not
 * run). Every statement is idempotent and contains no `?` (knex would read it
 * as a binding placeholder).
 *
 * Relative imports only: bundled into the standalone script.
 */

export const SEARCH_INDEX_MIGRATION_NAME = 'Migration20260925120000'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`

/* Maps as of Migration20260925120000, whose SQL this file must reproduce
 * exactly (migrationsSelfContained pins it). Later maps (event attendees, a
 * raw table with no query-index documents) are not part of that schema. */
const INDEXED_MAPS = DEFAULT_ENCRYPTION_MAPS.filter((m) => m.entityId !== 'customers:event_attendee')

/** Entity types whose query-index documents carry encrypted-by-design fields. */
function encryptedEntityTypes(): string[] {
  return INDEXED_MAPS.map((m) => m.entityId)
}

/** (entity_type, field) pairs search_tokens must not hold, profiles including their parent contact fields. */
function encryptedFieldPairs(): Array<[string, string]> {
  const pairs: Array<[string, string]> = []
  const parent = INDEXED_MAPS.find((m) => m.entityId === 'customers:customer_entity')?.fields ?? []
  for (const map of INDEXED_MAPS) {
    for (const f of map.fields) pairs.push([map.entityId, f.field])
    if (map.entityId === 'customers:customer_person_profile' || map.entityId === 'customers:customer_company_profile') {
      for (const f of parent) pairs.push([map.entityId, f.field])
    }
  }
  return pairs
}

export const SEARCH_INDEX_SCHEMA_SQL: string[] = [
  `create table if not exists "customer_search_tokens" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" uuid not null,
    "organization_id" uuid not null,
    "entity_type" text not null,
    "entity_id" uuid not null,
    "field" text not null,
    "token_hash" text not null,
    "created_at" timestamptz not null default now(),
    constraint "customer_search_tokens_entity_type_chk" check ("entity_type" in ('person', 'company', 'deal'))
  );`,
  // Lookup: every search filters tenant + organization + hash.
  `create index if not exists "customer_search_tokens_lookup_idx" on "customer_search_tokens" ("tenant_id", "organization_id", "token_hash");`,
  // Idempotent inserts, and the (entity_id) index: entity_id leads, so
  // per-entity replace/delete use it.
  `create unique index if not exists "customer_search_tokens_entity_uniq" on "customer_search_tokens" ("entity_id", "entity_type", "field", "token_hash");`,

  // Deletes can never leave derived data behind, whatever path deletes:
  // em.remove, nativeDelete, the GDPR purge, a raw soft delete.
  `create or replace function "customer_search_tokens_on_contact_change"() returns trigger language plpgsql as $$
begin
  if (TG_OP = 'DELETE') then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" in ('person', 'company');
    return OLD;
  end if;
  if (NEW."deleted_at" is not null and OLD."deleted_at" is null) then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" in ('person', 'company');
  end if;
  return NEW;
end
$$;`,
  `create or replace function "customer_search_tokens_on_deal_change"() returns trigger language plpgsql as $$
begin
  if (TG_OP = 'DELETE') then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" = 'deal';
    return OLD;
  end if;
  if (NEW."deleted_at" is not null and OLD."deleted_at" is null) then
    delete from "customer_search_tokens" where "entity_id" = OLD."id" and "entity_type" = 'deal';
  end if;
  return NEW;
end
$$;`,
  `create or replace function "customer_search_tokens_on_person_delete"() returns trigger language plpgsql as $$
begin
  delete from "customer_search_tokens"
   where "entity_id" = OLD."entity_id" and "entity_type" = 'person'
     and "field" in ('first_name', 'last_name', 'preferred_name', 'job_title');
  return OLD;
end
$$;`,
  `create or replace function "customer_search_tokens_on_company_delete"() returns trigger language plpgsql as $$
begin
  delete from "customer_search_tokens"
   where "entity_id" = OLD."entity_id" and "entity_type" = 'company'
     and "field" in ('legal_name', 'brand_name', 'domain', 'website_url');
  return OLD;
end
$$;`,
  `drop trigger if exists "customer_search_tokens_contact_trg" on "customer_entities";`,
  `create trigger "customer_search_tokens_contact_trg" after delete or update of "deleted_at" on "customer_entities" for each row execute function "customer_search_tokens_on_contact_change"();`,
  `drop trigger if exists "customer_search_tokens_deal_trg" on "customer_deals";`,
  `create trigger "customer_search_tokens_deal_trg" after delete or update of "deleted_at" on "customer_deals" for each row execute function "customer_search_tokens_on_deal_change"();`,
  `drop trigger if exists "customer_search_tokens_person_trg" on "customer_people";`,
  `create trigger "customer_search_tokens_person_trg" after delete on "customer_people" for each row execute function "customer_search_tokens_on_person_delete"();`,
  `drop trigger if exists "customer_search_tokens_company_trg" on "customer_companies";`,
  `create trigger "customer_search_tokens_company_trg" after delete on "customer_companies" for each row execute function "customer_search_tokens_on_company_delete"();`,
]

/**
 * Purge plaintext-equivalent copies of encrypted fields the Open Mercato query
 * index and search module wrote before this change:
 * - search_tokens: unkeyed SHA-256 of every word and 3+ char prefix of the
 *   decrypted names, emails, phones, titles, bodies (reversible with a word
 *   list), plus the optional raw `token` column; also tokens of the
 *   search_text aggregate and of encrypted custom fields.
 * - entity_indexes.doc.search_text: an aggregate of every string field,
 *   plaintext for rows indexed while their columns were still plaintext.
 * - vector_search (pgvector, created lazily by the search module): result
 *   title/subtitle/presenter/links in clear for contacts and deals.
 * Plaintext mapped values inside entity_indexes documents need the tenant key
 * to fix, so the backfill script encrypts those (`--phase index-docs`).
 */
export function searchIndexPurgeSql(): string[] {
  const types = encryptedEntityTypes().map(q).join(', ')
  const pairs = encryptedFieldPairs().map(([t, f]) => `(${q(t)}, ${q(f)})`).join(', ')
  // Each purge is skipped when its table does not exist (fresh or partial installs).
  const guarded = (tables: string[], statement: string) =>
    `do $purge$ begin
  if ${tables.map((t) => `to_regclass(${q(t)}) is not null`).join(' and ')} then
    ${statement}
  end if;
end $purge$;`
  return [
    guarded(['search_tokens'], `delete from "search_tokens" where ("entity_type", "field") in (values ${pairs});`),
    guarded(['search_tokens'], `delete from "search_tokens" where "entity_type" in (${types}) and "field" = 'search_text';`),
    guarded(['search_tokens', 'custom_field_defs'], `delete from "search_tokens" st using "custom_field_defs" d
      where d."entity_id" = st."entity_type"
        and st."field" in ('cf:' || d."key", 'cf_' || d."key")
        and (d."config_json"::jsonb ->> 'encrypted') = 'true';`),
    guarded(['search_tokens'], `update "search_tokens" set "token" = null where "token" is not null and "entity_type" in (${types});`),
    guarded(['entity_indexes'], `update "entity_indexes" set "doc" = "doc" - 'search_text' where "entity_type" in (${types}) and "doc" -> 'search_text' is not null;`),
    guarded(['vector_search'], `delete from "vector_search" where "entity_id" in (${types});`),
  ]
}

export const SEARCH_INDEX_DOWN_SQL: string[] = [
  `drop trigger if exists "customer_search_tokens_contact_trg" on "customer_entities";`,
  `drop trigger if exists "customer_search_tokens_deal_trg" on "customer_deals";`,
  `drop trigger if exists "customer_search_tokens_person_trg" on "customer_people";`,
  `drop trigger if exists "customer_search_tokens_company_trg" on "customer_companies";`,
  `drop function if exists "customer_search_tokens_on_contact_change"();`,
  `drop function if exists "customer_search_tokens_on_deal_change"();`,
  `drop function if exists "customer_search_tokens_on_person_delete"();`,
  `drop function if exists "customer_search_tokens_on_company_delete"();`,
  `drop table if exists "customer_search_tokens";`,
]

/**
 * Read-only counts of the plaintext-equivalent copies (what the purge would
 * remove). Used by the script's dry run. Each statement returns one `n`.
 */
export function searchIndexLeakCountSql(): Array<{ label: string; sql: string; requires: string }> {
  const types = encryptedEntityTypes().map(q).join(', ')
  const pairs = encryptedFieldPairs().map(([t, f]) => `(${q(t)}, ${q(f)})`).join(', ')
  return [
    { label: 'search_tokens rows hashed from encrypted fields', requires: 'search_tokens',
      sql: `select count(*)::bigint as n from "search_tokens" where ("entity_type", "field") in (values ${pairs})` },
    { label: 'search_tokens rows hashed from search_text of encrypted entities', requires: 'search_tokens',
      sql: `select count(*)::bigint as n from "search_tokens" where "entity_type" in (${types}) and "field" = 'search_text'` },
    { label: 'search_tokens rows hashed from encrypted custom fields', requires: 'search_tokens',
      sql: `select count(*)::bigint as n from "search_tokens" st join "custom_field_defs" d on d."entity_id" = st."entity_type" and st."field" in ('cf:' || d."key", 'cf_' || d."key") where (d."config_json"::jsonb ->> 'encrypted') = 'true'` },
    { label: 'search_tokens raw token column set (encrypted entities)', requires: 'search_tokens',
      sql: `select count(*)::bigint as n from "search_tokens" where "token" is not null and "entity_type" in (${types})` },
    { label: 'entity_indexes docs with search_text (encrypted entities)', requires: 'entity_indexes',
      sql: `select count(*)::bigint as n from "entity_indexes" where "entity_type" in (${types}) and "doc" -> 'search_text' is not null` },
    { label: 'vector_search rows of encrypted entities', requires: 'vector_search',
      sql: `select count(*)::bigint as n from "vector_search" where "entity_id" in (${types})` },
  ]
}
